### ISSUE TITLE
To check/fix for syntax errors with VoCol

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#10]
The ideal way to do it is by using Protégé before pushing. But even after that, you should check with VoCol to see the errors. For example, as you can check [here](http://vocol.iais.fraunhofer.de/sto/docs/syntax_validation.html) there is an error in the current version. So please fix the error.

**Comment by mubeequreshi** [comment]
I have complied and removed the errors from the current version of vocabulary.

**Comment by igrangel** [comment]
No. There are still errors. `rapper: Parsing sto.ttl with parser turtle rapper: Error - sto.ttl:244 - syntax error at '"' rapper: Failed to parse file ./sto.ttl turtle content rapper: Parsing returned 154 triples`
Please check VoCol every time you push.

**Comment by mubeequreshi** [comment]
I have checked the file syntax by using http://vocol.iais.fraunhofer.de/sto/docs/TurtleEditor/turtle-editor.html
editor it does not gives me syntax error and I have also tested our vocabulary syntax with an online turtle editor it also says there are not any more syntax errors
http://ttl.summerofcode.be/

**Comment by igrangel** [comment]
If you check it with the VoCol validator, i.e., http://vocol.iais.fraunhofer.de/sto/docs/syntax_validation.html, you will see what I´m saying.

**Comment by mubeequreshi** [comment]
Removed error .kinldy check it

**Comment by igrangel** [comment]
Ok, error removed, please always check with Protégé or any other related tool before pushing and, after pushing with VoCol.
