### ISSUE TITLE
Improving the README file. 

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#11]
Could you please improve the readme and provide a description of what is the ontology about. Its links in the web, i.e., VoCol, LOV, version, the other ontologies that are reused, etc?

**Comment by mubeequreshi** [comment]
Improved Readme file

**Comment by igrangel** [comment]
The license should be added. The links to the reused vocabularies should be added. Please fix typos.

**Comment by igrangel** [comment]
Please add links to the referenced vocabularies as I did with FOAF.

**Comment by ashuaru** [comment]
Vocabularies link added in the Readme file.

**Comment by igrangel** [comment]
Please add the name of the vocabulary as well. In addition, include this license https://creativecommons.org/licenses/by/3.0/
