### ISSUE TITLE
Why NIST concepts are included?

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#12]
NIST concepts should not be part of the STO ontology. If the NIST Ontology does not exist then we should create a rather small ontology to represent this but never include so many concepts in the STO ontology, e.g., [here](https://github.com/i40-Tools/StandardsVocabulary/blob/ab5a3f3077c3d991797990d69a93364eb5d6a839/sto.ttl#L75).

**Comment by mubeequreshi** [comment]
Until now I did not find any ontology like rami to model nist model information in standards vocabulary.@ashuaru also searched she also did not find so right now I have removed it
