### ISSUE TITLE
Provide correct documentation to all the classes and properties

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#14]
The basic is to have an `rdfs:label` and `rdfs:comment` for each one of the classes and properties like in [this](https://github.com/i40-Tools/StandardsVocabulary/blob/1a99be86dd6bdfd91c8c85c784eef1899a170418/sto.ttl#L549) example.

**Comment by mubeequreshi** [comment]
some of the classes have dc:description property .Do we also need to add comments property in that case as well ?

**Comment by igrangel** [comment]
Yes, let's put all elements with rdfs:comment and rdfs:label. In cases where is dc:description just replace with rdfs:comment.

**Comment by mubeequreshi** [comment]
okay got it

**Comment by igrangel** [comment]
@sebbader please provide `rdfs:label` and `rdfs:comment` for the classes you added, e.g., [IDSLayer](https://github.com/i40-Tools/StandardOntology/blob/765656f48a3946da5beca5c6b77305e0dff49b71/sto.ttl#L595) and [IDSPerspective](https://github.com/i40-Tools/StandardOntology/blob/765656f48a3946da5beca5c6b77305e0dff49b71/sto.ttl#L608).
