### ISSUE TITLE
To check the need of switching to OWL2 for sto:Standard

### ISSUE THREAD

**Issue by mmaltsev** [i40-Tools/StandardOntology#22]
The class [sto:Standard](https://github.com/i40-Tools/StandardsVocabulary/blob/47e99a1a19693f80662b5b32fb43cd5de7b6d6d6/sto.ttl#L1719) is now described by means of an individual. Thus, there should be investigated an option to switch to OWL2 in this case.

**Comment by igrangel** [comment]
1 - Every time you mention some specific concept from the ontology you should link it to the line of code where the concept is. You should also press (Y) to connect it to the specific commit. 

The `rdfs:isDescribedBy` property of the class [Standard](https://github.com/i40-Tools/StandardsVocabulary/blob/47e99a1a19693f80662b5b32fb43cd5de7b6d6d6/sto.ttl#L1719) is currently made by means of linking to an instance of the Ontology. Does this become the ontology OWL Full? Is this correct? How can this be improved/fixed?
