### ISSUE TITLE
Remove incorrect annotation properties

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#29]
Annotation properties should be removed or improved, e.g., internal ones [`sto:edition`](https://github.com/i40-Tools/StandardOntology/blob/65a6b662e754776bb39db85ef72515d18a1aa46d/sto.ttl#L97) and external ones like [`skos:prefLabel`](https://github.com/i40-Tools/StandardOntology/blob/65a6b662e754776bb39db85ef72515d18a1aa46d/sto.ttl#L93)

**Comment by PriyankaNanjappa** [comment]
Please refer to the [Push](https://github.com/i40-Tools/StandardOntology/commit/8cbdb8af667863daad0779e26e30edbd495668de).
