### ISSUE TITLE
sto:hasPages Property needs to be added to a Document 

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#30]

**Comment by igrangel** [comment]
You have to provide a description of the issue.

**Comment by PriyankaNanjappa** [comment]
We need to just add sto:hasPages Property

**Comment by igrangel** [comment]
And why you have to add this property? From which document you find out this?

**Comment by igrangel** [comment]
As for the documentation, there CANNOT exist any element in the ontology without `rdfs:label` and `rdfs:comment` as minimum requirements as [here](https://github.com/i40-Tools/StandardOntology/blob/e7a344e3e4318d3e04cd3a2e59bdd45dbd1d655f/sto.ttl#L408). Please fix it.

**Comment by TasneemRashid** [comment]
https://github.com/i40-Tools/StandardOntology/commit/343075fca79ca6a7edf01b0ab1b4bdf172302cce#diff-dce029c397c10dfbe56459fa65d111a7L410 
Updated the sto:hasPages property

**Comment by igrangel** [comment]
Please remove the `.` in the end. Comments can have `.` but labels don't.

**Comment by TasneemRashid** [comment]
https://github.com/i40-Tools/StandardOntology/commit/aa6260a68c30aea04ef30270dfab950fc3fdce28
removed the . from the label

**Comment by PriyankaNanjappa** [comment]
This issue can be closed
