### ISSUE TITLE
Add diagram and example of the Ontology

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#31]
To add a diagram and an example of the ontology to the readme page. This ontology can be used as a reference - https://github.com/HajoRijgersberg/OM

**Comment by igrangel** [comment]
[Here](https://github.com/i40-Tools/StandardOntology/tree/semantic_lab/Visualization), I have added resources for the visualization of the ontology in the readme file. 
You just have to install the [yEd editor](https://www.yworks.com/products/yed?) and modify these resources. 
On top of the Editor, you have to install the Grafoo plugin as explained [here](http://www.essepuntato.it/static/graffoo/graffoo.html) on the bottom of this page. 
Finally, you export the result as a PNG file and include it in the readme, similar to the example of the OM ontology referenced above.

**Comment by PriyankaNanjappa** [comment]
[Here](https://github.com/i40-Tools/StandardOntology/tree/be57daf6e1d8005dc2159026d6d82b0f9dbb3213/Visualization) are the modifications made.
