### ISSUE TITLE
has Edition Property for the standard.

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#33]
The documentation provided for dcterms:hasVersion is quoted below.
"Has Version: A related resource that is a version, edition, or adaptation of the described resource.
Notes: Dublin Core: This term is intended to be used with non-literal values as defined in the DCMI Abstract Model (http://dublincore.org/documents/abstract-model/). As of December 2007, the DCMI Usage Board is seeking a way to express this intention with a formal range declaration."

This is intended to be used with a non-literal value but I don't think it is defined as of now. My suggestion was to have our own sto:hasEdition Probaby just as a float value as of now.

**Comment by igrangel** [comment]
Please, when you implement something, write in the issue the link to the code. 
Before deciding to have our own `sto:hasEdition` property, please have a look at the [sioc:term_latest_version](http://rdfs.org/sioc/spec/#term_latest_version)` property. In addition, please consult the [Open Data Vocabularies service](http://lov.okfn.org/dataset/lov/terms?q=has%20edition). 
Please also have a look at the examples of the use of the lates_version property [here](https://www.w3.org/TR/prov-o/), in the PROV ontology.

**Comment by igrangel** [comment]
Have you found new insights regarding this issue?

**Comment by PriyankaNanjappa** [comment]
prov:wasRevisionOf and sioc:term_latest_version could be the 2 properties that talk about the different editions (History) of a Standards document.  hasEdition is still necessary to just depict the version number of a Document. The newly identified will help relate such different versions of the document

**Comment by igrangel** [comment]
What about `bibo:edition`, - http://lov.okfn.org/dataset/lov/vocabs/bibo?

**Comment by PriyankaNanjappa** [comment]
I think bibo:edition is a better choice in place of [sto:hasEdition](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L329) shall we make the change?

**Comment by igrangel** [comment]
Since the `bibo` ontology is not online, please keep the `sto:hasEdition`.
