### ISSUE TITLE
IEC TS 62832-1:2016 

### ISSUE THREAD

**Issue by TasneemRashid** [i40-Tools/StandardOntology#35]
TO/DOs 
Create:
1. class for ICS (International Classification for Standards)
2. object property hasICS
3. instance of ICS (25.040.40)
4. property for file size for IEC_TS 62832-1:2016
5. instance of IEC_TS 62832-1:2016

**Comment by igrangel** [comment]
Would have been better to split this issue into more detail ones.

**Comment by TasneemRashid** [comment]
Then I am closing it and creating new issues for each.
