### ISSUE TITLE
Create class for ICS  (International Classification for Standards)

### ISSUE THREAD

**Issue by TasneemRashid** [i40-Tools/StandardOntology#36]
Many technical specifications and standards have ICS which is used for classifying standards and normative documents in databases, libraries, etc. It is a  hierarchical classification which consists of three levels, e.g. ICS 25.040.40. Level 1 covers 40 fields of activity in standardization, and there are sub-divided group in level 2 and level 3.

**Comment by igrangel** [comment]
Could you exemplify this with one standard instance? or with one diagram?

**Comment by TasneemRashid** [comment]
Created the class : https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L616
Next I will include an example with a diagram for this concept.

**Comment by TasneemRashid** [comment]
![screenshot from 2018-06-22 15-12-22](https://user-images.githubusercontent.com/38520537/41778387-ea58ae3e-762e-11e8-94a5-ef328c1c4390.png)
From the [https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/international_classification_for_standards.pdf](url) document.

**Comment by igrangel** [comment]
I don´t think we need a class for this concept. Rather, we would need the classifications that are described in the document and then we do need a property for linking the Standard concept to the existing classifications. So, please give me reasons why having a class here.

**Comment by TasneemRashid** [comment]
There are some standards, which have multiple ICS. For example [this](https://webstore.iec.ch/publication/2245) one. So, my idea was to create each of the ICS as an instance of the class and link them with the property sto:hasICS.

**Comment by igrangel** [comment]
Yes, this design decision makes total sense. So please, implement it.

**Comment by TasneemRashid** [comment]
Ok.

**Comment by igrangel** [comment]
When you do that, please link the implementation here. After our common revision and approval, we can close this issue or kept it open for further discussions.

**Comment by TasneemRashid** [comment]
https://github.com/i40-Tools/StandardOntology/commit/afe741f17e5050276d832579aa7d291f188b3f04

**Comment by igrangel** [comment]
The schema seems to be fine. Can you further enrich it with instances?

**Comment by TasneemRashid** [comment]
@igrangel , all ICS instances are created for all the standards we have populated in the ontology. Please check if this issue can be closed.

**Comment by igrangel** [comment]
Coming back to the schema, what would be the relation between this class and the `sto:Domain`?

**Comment by PriyankaNanjappa** [comment]
I do not know the source from where sto:Domain is extracted from but the source where [sto:InternationalClassificationForStandards](https://github.com/i40-Tools/StandardOntology/blob/8cbdb8af667863daad0779e26e30edbd495668de/sto.ttl#L8950) is extracted is [this](https://www.iso.org/publication/PUB100033.html). ICS are classification codes that help classify the standards. Domain also talk about what the particular standard addresses probably but please provide source for [sto:Domain](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L699) .
