### ISSUE TITLE
TRF: Test Report Form of standards

### ISSUE THREAD

**Issue by TasneemRashid** [i40-Tools/StandardOntology#39]
Some standards has an information called TRF ( Test Report Form). This TRF is a publication type and has basic details like publication date, edition etc. For example [this standard](https://webstore.iec.ch/publication/21880) has a [TRF](https://webstore.iec.ch/publication/24732). 
Just a sample how TRF template may look like :
![TRF template](https://user-images.githubusercontent.com/38520537/42153124-7530d814-7de2-11e8-8e22-97ebcc2da4e8.jpg)

**Comment by igrangel** [comment]
This is fine but before going more into schema (TBox), I would like you to focus more on populating the existing KG with more instances.

**Comment by TasneemRashid** [comment]
I am working on the population. Just to address this concept I have created the issue.

**Comment by PriyankaNanjappa** [comment]
Since these documents rarely occur, we will consider them at a later time.

**Comment by PriyankaNanjappa** [comment]
This issue was sharing this information. we can close this issue i think. @TasneemRashid  could you please close this issue?

**Comment by TasneemRashid** [comment]
Issue closed.
