### ISSUE TITLE
Error Correction: sto:hasPages property

### ISSUE THREAD

**Issue by TasneemRashid** [i40-Tools/StandardOntology#41]
Property sto:hasPages has error in its' range. In some [`instances,`](https://github.com/i40-Tools/StandardOntology/blob/master/sto.ttl#L2451) ^^xsd:int is missing.

**Comment by igrangel** [comment]
Yes, this should be corrected. Please let me know when you have changed it for me to revise it.

**Comment by TasneemRashid** [comment]
@igrangel please check if this issue is ready to be closed.

**Comment by igrangel** [comment]
Yes, proper annotation of this property with `xsd:int`. We can close this issue.
