### ISSUE TITLE
No untyped individuals

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#42]
Unless there is a specific reason, there should not exist individuals which type is only `owl:NamedIndividual` as in [this](https://github.com/i40-Tools/StandardOntology/blob/53805cd665cc3eb2b60ae9911dd359298bcd2cfb/sto.ttl#L738) example. The individuals should always contain an `rdf:type` declaring which class they belong.

**Comment by PriyankaNanjappa** [comment]
Individuals of this kind have been removed. Please have a look and we can close the issue.

**Comment by igrangel** [comment]
![image](https://user-images.githubusercontent.com/7492788/44159532-feda9f80-a0b7-11e8-876c-ebf311ff03b8.png)
No, we can´t see the image for yourself how many untyped individuals are.

**Comment by PriyankaNanjappa** [comment]
Please have a look at this. Let me know if this is not the way. [Places and Country ](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L423)

**Comment by PriyankaNanjappa** [comment]
I need to understand [sto:hasClassification](https://github.com/i40-Tools/StandardOntology/blob/master/sto.ttl#L196) and [sto:StandardClassification](https://github.com/i40-Tools/StandardOntology/blob/master/sto.ttl#L669) to deal with some of these instances. What is the source of this information? I am a little hesitant to work on things that I don't understand well since I am not the original author of these things.

**Comment by igrangel** [comment]
The way you did it with Places and Countries is the right way. 
Please have a look at this example regarding `sto:hasClassification` and let me know if you understand this.
![image](https://user-images.githubusercontent.com/7492788/44201075-9daedc80-a148-11e8-962d-4745f75b85a4.png)

**Comment by igrangel** [comment]
Please have a look at [this](https://github.com/i40-Tools/StandardOntology/commit/0eb040f44994fe7506f10cd2b621789454032692) commit. Use protégé and texteditors at the same time.

**Comment by PriyankaNanjappa** [comment]
I understand the relationships and instance examples but I don't have necessary information to define these instances.  For example. What is [CommunicationSubModel](https://github.com/i40-Tools/StandardOntology/blob/master/sto.ttl#L869) . I tried to look at related content in the file but I don't know how to classify it.

**Comment by PriyankaNanjappa** [comment]
I am using protégé and sublime text editor parallely.

**Comment by igrangel** [comment]
Very valid question. Please have a look at [this](https://www.plattform-i40.de/I40/Redaktion/EN/Downloads/Publikation/structure-of-the-administration-shell.pdf;jsessionid=CF98AFEFB5DDD5AE1C807B53C746BAE9?__blob=publicationFile&v=7) document on page 19. Second, this the `rami:CommunicationSubModel` belongs to the rami ontology, thus it should be type of some of the rami classes.

**Comment by PriyankaNanjappa** [comment]
What is [sto:Concern](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L199). Source Please

**Comment by PriyankaNanjappa** [comment]
Also why are we redefining [sto:Configuration](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L1718) and using [rami:Configuration](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L5699). Its a source of confusion I think. Better to maintain one consistently.

**Comment by igrangel** [comment]
Yes, this is a mistake, there should only exist `rami:Configuration`.

**Comment by PriyankaNanjappa** [comment]
So, same applies to [sto:Communication](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L1695), [sto:ConditionMonitoring](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L1712) ?

**Comment by igrangel** [comment]
Please, when you do a link, press the key Y, otherwise, the link is lost.

**Comment by PriyankaNanjappa** [comment]
I understand the problem but did not understand when to press the Y.

**Comment by igrangel** [comment]
When you link to the code in Github, e.g., as in  `sto:Communication` above. It creates a unique link.

**Comment by igrangel** [comment]
Like here [sto:Communication](https://github.com/i40-Tools/StandardOntology/blob/2c7d58bef011f79982ee016b04bca9a7941de6df/sto.ttl#L1913).

**Comment by PriyankaNanjappa** [comment]
[sto:Communication](https://github.com/i40-Tools/StandardOntology/blob/2c7d58bef011f79982ee016b04bca9a7941de6df/sto.ttl#L1913). I have tried to do the same but I think the link does not work if there are modifications done to the file.

**Comment by igrangel** [comment]
Now it is correct. It does not matter if there are modifications. Well, in this case, `sto:Communication` is an instance of `rami:AdministrationShellSubModel`, so yes, it should be renamed to `rami:Communication`.

**Comment by igrangel** [comment]
![image](https://user-images.githubusercontent.com/7492788/44425888-76fc0600-a58d-11e8-9393-5ae242c87daa.png)
These few individuals are still without class. Please have a look to close this issue.

**Comment by PriyankaNanjappa** [comment]
All of the individuals are looked into and sorted.
