### ISSUE TITLE
Fixing properties in which the range is an URI

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#43]
These type of properties should have `rdfs:range` as `xsd:anyURI`, therefore the individuals that contain these properties should be fixed.

**Comment by igrangel** [comment]
This [commit](https://github.com/i40-Tools/StandardOntology/commit/fa7192228b34a17dffbb7bddd8e624046ffc194a) is an example of how to fix this issue.

**Comment by PriyankaNanjappa** [comment]
Looks like the current status of the file satisfies this property requirement. We can close this issue.
