### ISSUE TITLE
Fix syntax errors in Publication Date

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#45]

**Comment by TasneemRashid** [comment]
Date: 27-07-2018 (05:06 CEST) 
As per checking through protege, all dates are in correct input format. @igrangel please check.

**Comment by igrangel** [comment]
Yes, after correcting all the errors and understanding the correct syntax of `xsd:date` in the `sto:hasPublicationDate` property, we can close this issue.
