### ISSUE TITLE
Conflicts in sto.ttl (master)

### ISSUE THREAD

**Issue by sebbader** [i40-Tools/StandardOntology#46]
There are two (minor) conflicts in the master branch:
https://github.com/i40-Tools/StandardOntology/blob/4218e3304be0aa9d6276bca76137a73820b36aa4/sto.ttl#L2465
https://github.com/i40-Tools/StandardOntology/blob/4218e3304be0aa9d6276bca76137a73820b36aa4/sto.ttl#L3601

**Comment by igrangel** [comment]
They should be solved [here](https://github.com/i40-Tools/StandardOntology/commit/e9790186db915233c28134b9074aeb9d2a10ac41).
