### ISSUE TITLE
has Classification Property 

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#48]
Can anybody help me with the meaning and the source of information for the value of the property "has Classification"?

**Comment by igrangel** [comment]
Could you please point to the property in the ontology?

**Comment by PriyankaNanjappa** [comment]
This one [has Classification](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L251). we need to understand this to make relevant changes.
