### ISSUE TITLE
Target Concern Property needs Correction

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#50]
[Target Concern](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L99) Please check this out

**Comment by sebbader** [comment]
Can you provide me some more details on the issue? The link points to `om2:hasUnit rdf:type owl:AnnotationProperty .`

**Comment by PriyankaNanjappa** [comment]
[Target Concern](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L199) This is what I was referring to. But with the recent reading that I was doing, I understood why the subject is 
a URI in this triple. That was my primary concern in reporting this as an issue. False alarm. Sorry. Could you please direct me to the resource which led to the creation of this class and Property ?

**Comment by sebbader** [comment]
[ISO 42010](https://www.iso.org/standard/50508.html) specifies Concerns and other concepts/relations regarding Software Architectures. If you need further information, I also have access to the specification.

**Comment by PriyankaNanjappa** [comment]
Please give me any related resource available that connects a standard to sto:Concern. For example, [sto:CardinalityOfDataSources](https://github.com/i40-Tools/StandardOntology/blob/semantic_lab/sto.ttl#L1869) how is this a concern and how are standards related to this concern?
