### ISSUE TITLE
Leftovers in sto.ttl

### ISSUE THREAD

**Issue by sebbader** [i40-Tools/StandardOntology#51]
There is a 'Null'  entity in the ontology:
[`<https://w3id.org/i40/sto#>`](https://github.com/i40-Tools/StandardOntology/blob/2c7d58bef011f79982ee016b04bca9a7941de6df/sto.ttl#L1468)
For me, it looks like the combined leftovers of several changes/deletions.

**Comment by igrangel** [comment]
Could you please point out to the specific lines?

**Comment by sebbader** [comment]
[https://github.com/i40-Tools/StandardOntology/blob/2c7d58bef011f79982ee016b04bca9a7941de6df/sto.ttl#L1468](https://github.com/i40-Tools/StandardOntology/blob/2c7d58bef011f79982ee016b04bca9a7941de6df/sto.ttl#L1468) 
(also hidden in line 2 of my post :-) )

**Comment by igrangel** [comment]
Delete in [this](https://github.com/i40-Tools/StandardOntology/commit/1ca1793ef46b0342916278c8b681dc9fc8d1c5f1) commit. Check it out.

**Comment by sebbader** [comment]
perfect, then I close the issue
