### ISSUE TITLE
sto:hasTag punning as DataProperty and ObjectPropery

### ISSUE THREAD

**Issue by SpyrosKou** [i40-Tools/StandardOntology#55]
Hello again,
I noticed that sto:hasTag is declared both as a DataProperty and an ObjectPropery.
In particular:

```
###  https://w3id.org/i40/sto#hasTag
sto:hasTag rdf:type owl:ObjectProperty ;
           rdfs:domain sto:Publication .
```

```
###  https://w3id.org/i40/sto#hasTag
sto:hasTag rdf:type owl:DatatypeProperty ;
           rdfs:range muto:Tag ,
                      rdfs:Literal .
```
The individuals currently using the sto:hasTag exclusively use it as a DataProperty. (138 occurencies)
Perhaps it would be best to remove the ObjectPropery sto:hasTag definition since punning an IRI for more than one property types is currently unsupported.
See: https://www.w3.org/TR/owl2-new-features/#F12:_Punning

I could create a pull request if you agree.

**Comment by igrangel** [comment]
Yes, definitely a mistake. The initial idea was to reuse the `muto:tag` but it was complicated for the need we have. So, please go ahead.

**Comment by igrangel** [comment]
I merged everything into the master branch since we had other branches but I think now is fine.

**Comment by SpyrosKou** [comment]
Thank you,

I created a pull request.

**Comment by igrangel** [comment]
Please, create a link to the line of code when this type of issues occur.
