### ISSUE TITLE
Properties: hasDBPediaResource, hasWikipediaArticle and hasOfficialResource 

### ISSUE THREAD

**Issue by SpyrosKou** [i40-Tools/StandardOntology#57]
Hello, 

I would like to share the following findings:
Currently the following properties are defined as data properties:
https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L487

https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L515

https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L577

However their usage syntax implicitly defines them as ObjectProperties. For example: 

https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L1556
https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L1557
https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L1558

For example the syntax to use an xsd:anyUri in a dataProperty should be:
 sto:hasWikipediaArticle "https://en.wikipedia.org/wiki/American_National_Standards_Institute?oldformat=true"^^xsd:anyURI .

See also: [https://www.w3.org/TR/swbp-xsch-datatypes/]

Potential solutions could be to update the syntax as in a dataProperty type.
Or change the declaration of these properties to suitable property types.

Thank you

**Comment by igrangel** [comment]
Some properties were as you mentioned and there were raising some errors in Protégé. As they are now, no errors occur when the reasoner in Protégé is used.
