### ISSUE TITLE
sto:hasDomain usage as DataProperty

### ISSUE THREAD

**Issue by SpyrosKou** [i40-Tools/StandardOntology#58]
Hello,

I would like to share the following finding:
While the sto:hasDomain is declared as an ObjectProperty:
https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L346

There are 4 occurrences where it is used as a DataProperty and hence, making a dataProperty-ObjectProperty punning.

https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L3728

https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L5529

https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L6007

https://github.com/i40-Tools/StandardOntology/blob/e89369452d28773dba413b3aed5834636d0b4787/sto.ttl#L6561

Thank you

**Comment by igrangel** [comment]
Thanks again for pointing out this error. A solution for this would be to convert the literals into instances of the `sto:Domain` class.

**Comment by igrangel** [comment]
Solved in [this ](https://github.com/i40-Tools/StandardOntology/commit/e374597657cf296dca629beeb92f4d0a3b9424c8)commit.
