### ISSUE TITLE
ISO/IEC Standards

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#59]
Can we name the ISO/IEC standards as is in the resources rather than creating 2 different instances as in [example](https://github.com/i40-Tools/StandardOntology/blob/ab730bd6a12b2eac0ea95cfa6970dcc168eb7fd0/sto.ttl#L3619) . Since in resources in official resources [IEC](https://webstore.iec.ch/publication/9602) and [ISO](https://www.iso.org/standard/39479.html) both specify it as ISO/IEC 11404 rather than 2 instances ISO 11404 and IEC 11404 which are then specified to be same.

**Comment by igrangel** [comment]
One of the most important things we are doing is integrating information. At this level, we are doing this manually but we should be capable to describe the process in a way that it can be easily automated. 
Having two instances would help us to better describe the domain and do the integration, since if in only one example, the standards are named differently or only with IEC or ISO, then we would need the two instances.

**Comment by PriyankaNanjappa** [comment]
As far as I researched on the internet, they are always referred to as ISO/IEC ........ and so on.  A web search "ISO 11404" produces results for ISO/IEC 11404 and none of the results show IEC 11404 or ISO 11404. That was the concern. If it makes sense to have them separately for some reason and does not hurt the semantics, then I guess we can let it be.

**Comment by sebbader** [comment]
The point is which resource the refer to. While we are usually talking/thinking about e.g. ISO/IEC 11404, the informtation resource (=the document providing/containing the resource) is actually either ISO 11404 or IEC 11404. So, they are different entities and therefore have to be treated differently. The main question is whether we want to mix the resource (ISO/IEC 11404) and it's information carrier. In my view, we should not.

**Comment by igrangel** [comment]
Have a look at this resource - https://www.tititudorancea.com/z/iso_11404.htm

**Comment by igrangel** [comment]
As @sebbader says and the example above confirms, they are equivalent but treated differently in different places. Thus, we should keep them separate.

**Comment by PriyankaNanjappa** [comment]
Alright then. We will maintain the same format of representation. Thanks for the clarification!

**Comment by PriyankaNanjappa** [comment]
Issue can be closed.
