### ISSUE TITLE
General open Documents of Standards available online

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#60]
Do we have a property that represents the open documents(resources) available for a Standard? As in [IEC 11404](https://github.com/i40-Tools/StandardOntology/blob/ab730bd6a12b2eac0ea95cfa6970dcc168eb7fd0/sto.ttl#L6475) has [this open document ](http://www.open-std.org/jtc1/sc22/open/n3620.pdf) available. It is good to have that information also available in the sto.ttl file if we are going to account this in our statistics .  

I do not see a way to represent this as of now.
I would suggest we add a datatype property similar to [sto:hasOfficialResource](https://github.com/i40-Tools/StandardOntology/blob/ab730bd6a12b2eac0ea95cfa6970dcc168eb7fd0/sto.ttl#L516). " hasOpenResource "

**Comment by igrangel** [comment]
Sounds good, but before adding the property, what would you put in the description of it? I mean, what would be in the `rdfs:comment` of that property?

**Comment by PriyankaNanjappa** [comment]
"points to the URLs of the resources(documents) openly available for the standard ".

**Comment by igrangel** [comment]
Please go ahead with this property

**Comment by PriyankaNanjappa** [comment]
This is dealt with. We can close this issue.
