### ISSUE TITLE
Mapping Standards to their classification in a Reference Architecture

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#61]
I was wondering how to map a standard to it's most relevant classification according to a Reference Architecture. In other words, how can we identify that a particular standard belongs to which part of RAMI or IICF or ISA?

**Comment by igrangel** [comment]
The standards have to be mapped to only to their most relevant classification but to all the classifications that can be found in the Standardization Frameworks. The standardization frameworks have dimensions, layers. These dimension and layers comprise functions that the standards make. For example, in the RAMI4.0 specification, you can find this.

**Comment by PriyankaNanjappa** [comment]
I am researching about reference architectures and RAMI in specific. For a random standard relevant for industry 4.0 like [ ISO 11783-1:2017](https://www.iso.org/standard/57556.html), if we read the explanation on the website about the standard, I would categorize it under "Communication" layer of Architecture layers. We could say it is concerned with "Control device" in second dimension of RAMI . I am not sure how to decide whether it is categorized under "Type" or "instance" of the 3rd dimension of RAMI. 

If we find a way to categorize standards effectively and have this information in STO ontology, and the RAMI ontology itself depicts similarities and differences between different architectures, the standards can be easily mapped to parts of different architectures.

Will this be a helpful development in what we are trying to achieve in terms of Inter-operability of standards?

**Comment by sebbader** [comment]
Is this still an issue?

**Comment by PriyankaNanjappa** [comment]
We can close this issue.
