### ISSUE TITLE
Representing history of a Standad document 

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#62]
[IEC 61850 Part 4](https://webstore.iec.ch/publication/6011) has two editions of the given standard. [Edition 2](https://webstore.iec.ch/publication/6011) is the currently valid version and [Edition 1](https://webstore.iec.ch/publication/20074) is the withdrawn version.  [prov:wasRevisionOf](https://www.w3.org/TR/prov-o/) can be used to link the 2 versions. 
We now have to revise the naming convention for the Standard again. We have to introduce "Edition part" in the name as in the [example](https://github.com/i40-Tools/StandardOntology/blob/c1d5e1d4ba0b06cd130ffaed6970fd2ae9d3c8b1/sto.ttl#L5979) to uniquely identify a standard document.

**Comment by sebbader** [comment]
I am not sure if I fully understand this. With 'name' you are refering to the URI or the label? Your example looks fine, as long as the URIs are unique and the pointers to previous versions are supplied, we should be good.

**Comment by PriyankaNanjappa** [comment]
I was referring to the URIs . This issue was to update everyone about the requirement to add version details in the URIs to  maintain uniqueness. We can close the issue since we have clarity on that.
