### ISSUE TITLE
Technical committees for Standards from different standard organisations 

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#63]
Different standard Organisations have their Technical Committees which are distinct from one another. We need to find a way to represent them differently. Technical Committees for ISO is [this](https://www.iso.org/technical-committees.html)  and for IEC is [this.](https://www.iec.ch/dyn/www/f?p=103:6:0##ref=menu)

**Comment by igrangel** [comment]
I propose to create a general class TechnicalCommitte. Then, create two subclasses describing the ISO and the IEC. The properties that are repeated will go to the general class. The rest to the respective classes.

**Comment by PriyankaNanjappa** [comment]
The changes are made according to your suggestion @igrangel . We can close this issue.
