### ISSUE TITLE
Modeling related Concern 

### ISSUE THREAD

**Issue by PriyankaNanjappa** [i40-Tools/StandardOntology#66]
DIN SPEC 16593-1,Reference Model for Industrie 4.0 Service Architectures - 
DIN SPEC 91345 Reference Architecture Model Industrie 4.0 
IEC PAS 63088 Ed. 1, Smart Manufacturing – Reference Architecture Model Industrie 4.0
IEC 61360 and ISO 13584-42.
IEC 62264
IEC 62832
IEC 62890 and DIN 77005-1
(“Life cycle Management” and “Life cycle record of technical objects” respectively

**Comment by igrangel** [comment]
No idea why this issue is opened

**Comment by sebbader** [comment]
I guess we know how to do it by now, right? Can be closed in my view.
