### ISSUE TITLE
Organizations should be linked to Countries

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/StandardOntology#9]
The Organization Instances, e.g., [MIIT](https://github.com/i40-Tools/StandardsVocabulary/blob/86658ae485bfd92d64c403198596395c84584229/sto.ttl#L86) should be linked the Country they belong.

**Comment by mubeequreshi** [comment]
Yes you are right I will update it soon for all of our Reference Models.

**Comment by mubeequreshi** [comment]
Added country information for organization.

**Comment by igrangel** [comment]
Could you point at least one line of code when this adding was done?

**Comment by mubeequreshi** [comment]
Irlan can you please bit elaborate a context "at least one line of code when this adding was done" I did not understand it.

**Comment by igrangel** [comment]
Click [here](https://github.com/i40-Tools/StandardsVocabulary/blob/a70c7a2ac411b7b4137620c70ad98c345f2c3c1a/sto.ttl#L107)

**Comment by mubeequreshi** [comment]
Oka.Thankx

**Comment by mubeequreshi** [comment]
updated structure of countries

**Comment by igrangel** [comment]
For example, in which line?

**Comment by mubeequreshi** [comment]
#https://github.com/i40-Tools/StandardsVocabulary/commit/6e28d10f0ada6c5386b0d60a190527ade9ec9815

**Comment by igrangel** [comment]
You don't have to create Country instances in the ontology, .e.g., https://github.com/i40-Tools/StandardsVocabulary/blob/6e28d10f0ada6c5386b0d60a190527ade9ec9815/sto.ttl#L61, but to reuse existing datasets like DBpedia.

**Comment by igrangel** [comment]
Also, check please the definitions of the domain and ranges of this property - https://github.com/i40-Tools/StandardsVocabulary/blob/6e28d10f0ada6c5386b0d60a190527ade9ec9815/sto.ttl#L43

**Comment by mubeequreshi** [comment]
Yes ,I have update them with Dpedia datasets of country so I don't need to create own instance of country and also I have removed following  geo vocab properties. https://github.com/i40-Tools/StandardsVocabulary/blob/6e28d10f0ada6c5386b0d60a190527ade9ec9815/sto.ttl#L43

**Comment by igrangel** [comment]
The Countries should not be part of the STO Ontology like in [this](https://github.com/i40-Tools/StandardsVocabulary/blob/ab5a3f3077c3d991797990d69a93364eb5d6a839/sto.ttl#L48) case. Cases like the above mentioned should be deleted and only the reference included and the DBPedia namespace in the head.

**Comment by mubeequreshi** [comment]
updated countries information by using dbpedia resources
